import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { AppContext, AppmanagerContext } from "../component/AppContext";
import { ThemeContext } from "../component/Context/ThemeContext";
import { useState } from "react";
import { lightTheme } from "../utils/theme";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <ThemeContext.Provider value={lightTheme}>
        <AppmanagerContext>
          <Head>
            <title>Welcome to My Weblog</title>
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1, minimum-scale=1"
            />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <Component {...pageProps} />
        </AppmanagerContext>
      </ThemeContext.Provider>
    </>
  );
}

export default MyApp;
function useAppManager() {
  throw new Error("Function not implemented.");
}
